abstract final class AppRoutes {
  static const splash = '/';
  static const instructions = '/instructions';
  static const securityGate = '/security/gate';
  static const securityError = '/security/error';
  static const airplaneModeRequired = '/security/airplane-mode';
  static const wifiModeRequired = '/security/wifi-mode';
  static const vpnLockdownRequired = '/security/vpn-lockdown';
  static const developerModeRequired = '/security/developer-mode';
  static const cameraPermissionRequired = '/security/camera-permission';
  static const login = '/login';
  static const examWaiting = '/exam/waiting';
  static const examSubmitReview = '/exam/submit-review';
  static const mcqExam = '/exam/mcq';
  static const fillBlankExam = '/exam/fill-blank';
  static const writtenExam = '/exam/written';
  static const finishExam = '/exam/finish';
  static const violation = '/violation';
}
